server:
  port: 8090


spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://cdb-5gkdgdz8.bj.tencentcdb.com:10170/test_schema
      username: root
      password: root123456
    db2:
      jdbc-url: jdbc:mysql://cdb-5gkdgdz8.bj.tencentcdb.com:10170/bak_schema
      username: root
      password: root123456

#  mybatis.config-location=classpath:mybatis-config.xml
#mybatis:
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  type-aliases-package: com.duing.model
#  config-location: classpath:mybatis-config.xml

#  mybatis.mapper-locations=classpath*:/mappers/*.xml
#  mybatis.type-aliases-package=sample.mybatis.domain